services:
  database:
    container_name: my-database
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: my-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
